# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
    directory: "/" # Location of package manifests (requirements*.txt)
    commit-message:
      prefix: "META(pip,deps)"
      prefix-development: "TOOL(pip,deps)"
      include: "scope"
    assignees: 
      - "AlexLemna"
    labels:
      - "dependencies"
      - "bot"
    schedule:
      interval: "weekly"
      day: "sunday"
    
    
    
